#!/bin/sh
tmux_init()
{
    tmux new-session -s "base" -d -n "local"    # 开启一个会话
    tmux select-window -t "local"
    tmux split-window -h -p 20                  # 开启一个竖屏
    tmux select-pane -t 1
    tmux split-window -v -p 25                  # 开启一个横屏,并执行top命令
    tmux select-pane -t 0
    tmux -2 attach-session -d                   # tmux -2 强制启用256color，连接已开启的tmux
}

# 判断是否已有开启的tmux会话，没有则开启
[ -z "$TMUX" ] && (tmux attach || tmux_init)
